TEST_SOURCES := $(wildcard test_*.c)
TEST_DEP_SOURCES := ../../../os/util/memory.c
TEST_DEP_SOURCES += ../../../os/util/crypt-crc32.c
TEST_DEP_SOURCES += ../../../os/util/string.c

include ../../Makefile.in
